#!/bin/bash

if [[ $1 == "" ]] ; then
	echo "Sets up a repository for Intranet 2 development"
	echo "Usage: setup [type] [username]"
	echo "[type] is one of: home humboldt"
	echo "[username] is optional"
	echo
	echo "Assuming [type] is humboldt..."
	echo
	arg="humboldt"
else
	arg=$1
fi
if [[ $arg == "home" ]] ; then
	./scripts/setup.home $2
else 
	if [[ $arg == "humboldt" ]]; then
		./scripts/setup.humboldt $2				
	else
		echo "Type \"$arg\" not recognized; should be either humboldt or home."
	fi
fi


