<a href="[<$I2_ROOT>]eighthinfo">Back to Eighth Period Info home</a>
<p>Eighth period is an opportunity for students to meet with other students who share a common interest, (such as intramural sports, clubs or academic teams, etc.) under the supervision of a faculty/staff representative. Teachers within each department also offer tutoring and make up work in curricular subjects at this time.  Study halls are available for those who wish to work on assignments. These activities are offered as a part of the school day so that every student may participate in some activity that interests him/her. Regular buses do not leave until after eighth period. </p>

<p>On anchor day 8th periods (called "TA" and normally held on Mondays), students are assigned to a specific teacher/advisor (TA) within grade level. The time is used for administrative, guidance, or BBC (Building a Better Community) activities, class meetings, assemblies, video presentations, and discussions. </p>

<p>On even block days (Wed. and Fri.) students sign up for a different activity for A-block (2:20PM - 3:00PM) and B-block (3:10PM - 3:50PM) or decide to participate in the same activity for both blocks. More than 150 activities are offered and the list changes from year to year and during the year depending upon student interest.  Some activities are bi-weekly, some are monthly; in general there are 70- 80 choices for each block on any given day. The schedule is revised every eight weeks.  Most activities are student-led with the faculty/staff representative as an observer, which provides many opportunities for leadership roles for students within activities that interest them.</p>

<p>Students must select their activities before 12:30PM on the day of the activity.  They may select their activities on-line from home via their student account on the TJ Intranet, from most computers in the school, or in person at the Eighth Period Office (236 wk). Most activities are posted 8 weeks in advance, although last minute changes do occur. A complete listing of the schedule of activities offered for both blocks of the upcoming day is posted in advance at numerous locations throughout the building.  Students who do not select their activities by 12:30PM are automatically assigned to an Administrative Study Hall and they are expected to attend that study hall.</p>

<p>Eighth period is similar to what one might find as an after-school activity at a base school. Because of the geographic diversity of the TJ population, transportation issues would prevent many students from being able to participate.  Since 8th period is a part of the school day, the school must account for the whereabouts of each student during that time. Therefore, between 12:30PM and 2PM attendance lists are generated and room assignments finalized. Each activity sponsor is given an attendance roster for accountability purposes. At the end of the day the lists are collected, correlated with the school absentee list for the day, and attendance is recorded for each student and each activity.  Often this attendance information is used for PE credit, service hour credit and to determine how students are utilizing their eighth period time.  If a student is having academic difficulty, this information may be shared in a parent/counselor conference.  </p>

<p>Students are expected to attend their eighth period activities and to make certain that they are given attendance credit before leaving for the next activity. Eighth period attendance records are considered to be one measure of responsibility and reliability when considering students for leadership positions within the school, in preparing college recommendations, mentorship referrals or assigning parking spaces.  Students are encouraged to monitor their attendance record online and come to the Eighth Period Office as soon as possible to correct any errors that they believe might have been made. </p>

<p>A complete listing of the activities offered is available to anyone at any time in the Eighth Period Office.  Please keep in mind that the faculty/staff representatives listed this year may or may not change for next year.  Each September teachers have the opportunity to select the activities that they wish to sponsor for the coming year.</p>

<p>For more information about eighth period, you may call 703-750-5078.</p>
