<p>First, set up your proxy server by configuring your browser.  Detailed directions are at <a href="[<$I2_ROOT>]info/proxyinfo">[<$I2_ROOT>]info/proxyinfo</a></p>
<p><strong>After you have configured your browser or computer</strong> to access the databases via our proxy server, Zeus, you can access the library's subscription databases from the library's page at TJ's website at  <a href="http://www.tjhsst.edu/research-academics/library/databases.html">http://www.tjhsst.edu/research-academics/library/databases.html</a>.</p>

[<* include the autogenerated list *>]
[<* include file="info/links.tpl" *>]
