In order for the following links to work as expected, <b>if you are at home</b>, you first need to set your browser's proxy to <b>local.border.tjhsst.edu</b> on port <b>8080</b> (<a href="[<$I2_ROOT>]info/proxyinfo">Detailed directions</a>).
<ul>
[<* include the autogenerated list *>]
[< include file="info/links.tpl" >]
</ul>
