#!/bin/bash

test -f config.ini.php5 || cd ${HOME}/intranet2

echo "Creating mysql databases..."
./scripts/mysqltables
echo "Populating DBs"

pass=`./scripts/mysqlpass`

for i in `ls -1 --color=never mysql/base/*.sql`; do
	mysql -u iodine --password="${passwd}" -D iodine -e "source $i"
done

echo "Creating LDAP base"
ldapadd -Q -c -f ldap/base.ldif
ldapmodify -Q -c -f ldap/base.ldif
