#!/bin/bash

cd ${HOME}/intranet2

echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "!!!!!         Warning!         !!!!!"
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo
echo "      ALL DATA WILL BE DELETED!     "
echo
echo "Pausing for ten seconds..."
sleep 5
echo "5"
sleep 1
echo "4"
sleep 1
echo "3"
sleep 1
echo "2"
sleep 1
echo "1 ...  LAST CHANCE!"
sleep 1
echo "Okay."

echo "Extracting MySQL password from config.ini..."
passwd=`scripts/mysqlpass`
echo "Done!"

cd mysql

echo "Executing all .sql files in the mysql/ directory..."
for i in `ls -1 *.sql`; do 
		  mysql -D iodine -u iodine --password=$passwd -e "source $i"
done

echo "Adding modules to intraboxes..."
scripts/addboxes
echo "Done"

echo "Done!"
