DROP TABLE IF EXISTS eighth_postsigns;
CREATE TABLE eighth_postsigns(
	cid MEDIUMINT(8) UNSIGNED NOT NULL,
	uid MEDIUMINT(8) UNSIGNED NOT NULL,
	time DATETIME NULL DEFAULT NULL,
	fromaid MEDIUMINT UNSIGNED NOT NULL,
	toaid MEDIUMINT UNSIGNED NOT NULL,
	bid MEDIUMINT UNSIGNED NOT NULL
);
