DROP TABLE IF EXISTS eighth_printers;
CREATE TABLE eighth_printers(
	id MEDIUMINT UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(id),
	ip VARCHAR(15) NOT NULL,
	name VARCHAR(64) NOT NULL,
	is_selected TINYINT(1) NOT NULL DEFAULT 0
);
