DROP TABLE IF EXISTS eighth_rooms;
CREATE TABLE eighth_rooms (
	rid MEDIUMINT UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(rid),

	name VARCHAR(63) NOT NULL,

	capacity INT NOT NULL DEFAULT '-1'
);
