DROP TABLE IF EXISTS eighth_periods;
CREATE TABLE eighth_periods (
	bid MEDIUMINT UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(bid),

	date DATE NOT NULL,

	block ENUM('A','B') NOT NULL,

	locked TINYINT(1) NOT NULL DEFAULT '0'
);
