DROP TABLE IF EXISTS eighth_activities;
CREATE TABLE eighth_activities (
	aid MEDIUMINT UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(aid),

	name VARCHAR(63) NOT NULL,

	sponsors VARCHAR(127) NOT NULL,

	rooms VARCHAR(127) NOT NULL,

	description VARCHAR(255) NOT NULL DEFAULT '',

	restricted TINYINT(1) NOT NULL DEFAULT '0'
);
