DROP TABLE IF EXISTS eighth_sponsors;
CREATE TABLE eighth_sponsors (
	sid MEDIUMINT UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(sid),

	fname VARCHAR(63) NOT NULL,

	lname VARCHAR(127) NOT NULL,

	pickup VARCHAR(5),

	userid MEDIUMINT(8) UNIQUE NOT NULL
);
