DROP TABLE IF EXISTS event_blocks;
CREATE TABLE event_blocks(
	id INTEGER UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(id),
	startdt DATETIME NOT NULL DEFAULT 0,
	enddt DATETIME NOT NULL DEFAULT 0
);
