DROP TABLE IF EXISTS event_signups;
CREATE TABLE event_signups(
	eid INTEGER UNSIGNED NOT NULL,
	uid INTEGER UNSIGNED NOT NULL,
	paid TINYINT(1) NOT NULL DEFAULT 0,
	amount INTEGER UNSIGNED NOT NULL,
	type INTEGER UNSIGNED NOT NULL
);
