DROP TABLE IF EXISTS homecoming_votes;
CREATE TABLE homecoming_votes (
	uid MEDIUMINT UNSIGNED NOT NULL UNIQUE,
	PRIMARY KEY(uid),
	grade MEDIUMINT UNSIGNED NOT NULL,
	KEY(grade),
	male MEDIUMINT UNSIGNED,
	female MEDIUMINT UNSIGNED
);
