DROP TABLE IF EXISTS nag_group_map;
CREATE TABLE nag_group_map(
	nid MEDIUMINT UNSIGNED NOT NULL,
	gid MEDIUMINT NOT NULL,
	PRIMARY KEY(nid,gid),
	active TINYINT(1) NOT NULL DEFAULT 0,
	critical TINYINT(1) NOT NULL DEFAULT 0
);
