DROP TABLE IF EXISTS podcast_permissions;

CREATE TABLE podcast_permissions(
	pid MEDIUMINT(8) UNSIGNED NOT NULL,
	gid MEDIUMINT(8) UNSIGNED NOT NULL,
	PRIMARY KEY(pid,gid),
	vote BOOLEAN NOT NULL DEFAULT 1,
	modify BOOLEAN NOT NULL DEFAULT 0,
	results BOOLEAN NOT NULL DEFAULT 0
);
