DROP TABLE IF EXISTS podcast_votes;
CREATE TABLE podcast_votes (
		  pid MEDIUMINT(8) UNSIGNED NOT NULL,
		  qid TINYINT(4) UNSIGNED NOT NULL,
		  aid SMALLINT(4) UNSIGNED NOT NULL,
		  uid MEDIUMINT(8) UNSIGNED DEFAULT 0,
		  PRIMARY KEY(pid,qid,aid,uid),
		  grade ENUM('9','10','11','12','STAFF') NOT NULL,
		  gender ENUM('M','F') DEFAULT NULL,
		  written MEDIUMTEXT DEFAULT NULL
);
