DROP TABLE IF EXISTS poll_votes;
CREATE TABLE poll_votes (
		  uid MEDIUMINT(8) UNSIGNED DEFAULT 0,
		  pid MEDIUMINT(8) UNSIGNED DEFAULT 0,
		  qid MEDIUMINT(8) UNSIGNED DEFAULT 0,
		  aid MEDIUMINT(8) UNSIGNED DEFAULT 0
);
