DROP TABLE IF EXISTS polls;
CREATE TABLE polls (
		  pid MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
		  PRIMARY KEY(pid),
		  name VARCHAR(128) NOT NULL DEFAULT '',
		  introduction MEDIUMTEXT NOT NULL DEFAULT '',
		  visible TINYINT(1) UNSIGNED DEFAULT 0,
		  startdt DATETIME NOT NULL DEFAULT 0,
		  enddt DATETIME NOT NULL DEFAULT 0
);
