DROP TABLE IF EXISTS poll_permissions;

CREATE TABLE poll_permissions(
	pid MEDIUMINT(8) UNSIGNED NOT NULL,
	gid MEDIUMINT(8) UNSIGNED NOT NULL,
	PRIMARY KEY(pid,qid),
	vote BOOLEAN NOT NULL DEFAULT 1,
	modify BOOLEAN NOT NULL DEFAULT 0,
	results BOOLEAN NOT NULL DEFAULT 0
);
