CREATE TABLE schedules(
	uid BIGINT NOT NULL UNIQUE,
	PRIMARY KEY(uid),
	p1 BIGINT DEFAULT 0,
	p2 BIGINT DEFAULT 0,
	p3 BIGINT DEFAULT 0,
	p4 BIGINT DEFAULT 0,
	p5 BIGINT DEFAULT 0,
	p6 BIGINT DEFAULT 0,
	p7 BIGINT DEFAULT 0
);
