[<*<a href="https://forge.tjhsst.edu/iodine/">Iodine TJforge site</a><br />>]
[<*<a href="http://iodine.tjhsst.edu/phpdoc/">Master Iodine documentation</a><br />>]
<a href="http://iodine.tjhsst.edu/hg/">Online HG browser</a><br />
<a href="https://iodine.tjhsst.edu/">Main version of Iodine running</a><br /><br />
<span class="bold">Admin tools:</span><br />
<a href="[<$I2_ROOT>]mysqlinterface">MySQL Interface</a><br />
<a href="[<$I2_ROOT>]ldapinterface">LDAP Interface</a><br />
<a href="[<$I2_ROOT>]codeinterface">Code interface</a><br />
<a href="[<$I2_ROOT>]groups">Groups Interface</a>
