INSERT INTO groups (name,description) VALUES('admin_all','The grand admin group');
INSERT INTO groups (name,description) VALUES('admin_ldap','The LDAP admin group');
INSERT INTO groups (name,description) VALUES('admin_mysql','The MySQL admin group');
INSERT INTO groups (name,description) VALUES('admin_eighth','The eighth admin group');
INSERT INTO groups (name,description) VALUES('admin_groups','The groups admin group');
INSERT INTO groups (name,description) VALUES('admin_news','The news admin group');
INSERT INTO intrabox (name,display_name) VALUES('birthdays','birthdays');
INSERT INTO intrabox (name,display_name) VALUES('eighth','eighth');
INSERT INTO intrabox (name,display_name) VALUES('news','news');
INSERT INTO intrabox (name,display_name) VALUES('studentdirectory','Student Directory');
INSERT INTO intrabox (name,display_name) VALUES('filecenter','Access Your Files');
INSERT INTO intrabox (name,display_name) VALUES('scratchpad','Scratchpad');
INSERT INTO intrabox (name,display_name) VALUES('mail','mail');
