INSERT INTO intrabox (name,display_name) VALUES('news','News');
INSERT INTO intrabox (name,display_name) VALUES('eighth','Eighth Period');
INSERT INTO intrabox (name,display_name) VALUES('mail','Your Mail');
INSERT INTO intrabox (name,display_name) VALUES('filecenter','Your Files');
INSERT INTO intrabox (name,display_name) VALUES('birthdays','Birthdays');
INSERT INTO intrabox (name,display_name) VALUES('studentdirectory','Student Directory');
INSERT INTO intrabox (name,display_name) VALUES('links','Useful Links');
INSERT INTO intrabox (name,display_name) VALUES('scratchpad','ScratchPad');
INSERT INTO intrabox (name,display_name) VALUES('seniors','Senior College Destinations');
INSERT INTO intrabox (name,display_name) VALUES('weather','TJ Weather Info');
INSERT INTO intrabox (name,display_name) VALUES('devlinks','Developer Links');
INSERT INTO intrabox (name,display_name) VALUES('polls','Polls');
INSERT INTO intrabox (name,display_name) VALUES('countdown','Graduation countdown');
INSERT INTO intrabox (name,display_name) VALUES('testing','Testing Information');
INSERT INTO intrabox (name,display_name) VALUES('majora','Majora\'s Mask Countdown');
INSERT INTO intrabox (name,display_name) VALUES('bellschedule','Bell Schedule');
